"""Password hashing and session cookie helpers for V2 auth.

Sb_AUTH_PASSLIB_TO_BCRYPT_DIRECT_01 — hashing calls the `bcrypt` package
directly. passlib 1.7.4 is unmaintained since 2020 and cannot load bcrypt 5: its
backend self-test hashes a 255-byte probe, which bcrypt 5 refuses, so backend
detection fails and every hash/verify raises. That single dependency was what
pinned the project to `bcrypt<5`.

Nothing about the stored digests changes. Both layers write `$2b$` at cost 12,
and each verifies the other's output — measured before the switch, and pinned by
`tests/test_auth_fixture_fastpath.py`, whose fixture hash was generated by
passlib and must keep verifying.

Passwords are stored as bcrypt hashes. The session
token is a signed cookie produced by itsdangerous. No JWT, no
OAuth, no external provider — just a simple server-side session
cookie for an SSR app.

Cookie name: `session_token`
Cookie content: itsdangerous-signed JSON `{"user_id": <int>}`
Cookie flags: httponly, samesite=lax, secure in production
"""
from __future__ import annotations

from typing import Optional

import bcrypt
from itsdangerous import BadSignature, URLSafeTimedSerializer
from sqlalchemy import select
from sqlalchemy.orm import Session
from starlette.requests import Request
from starlette.responses import Response

from app.config import get_settings
from app.models.user import User
from app.services.password_policy import (
    TOO_LONG_MESSAGE,
    PasswordTooLongError,
    is_password_too_long,
)

SESSION_COOKIE = "session_token"
SESSION_MAX_AGE = 30 * 86400  # 30 days

#: bcrypt work factor. 12 is what passlib used by default, so hashes written
#: before and after this migration are indistinguishable — same `$2b$12$` prefix,
#: no re-hash, no forced reset. Raising it later is a separate decision with a
#: latency cost, not a side effect of dropping passlib.
BCRYPT_ROUNDS = 12


def hash_password(plain: str) -> str:
    """Hash a password with bcrypt, or refuse loudly.

    Raises :class:`PasswordTooLongError` past 72 bytes instead of letting bcrypt
    silently ignore the tail. The route-level policy already rejects such inputs
    (`Sb_AUTH_PASSWORD_LENGTH_01`); this is the belt to that pair of braces, and
    it also covers callers outside the request path — `scripts/create_user.py`
    has no route to validate it.
    """
    if is_password_too_long(plain):
        raise PasswordTooLongError(TOO_LONG_MESSAGE)
    return bcrypt.hashpw(plain.encode("utf-8"), bcrypt.gensalt(BCRYPT_ROUNDS)).decode("utf-8")


def verify_password(plain: str, hashed: str) -> bool:
    """Check a password against a stored bcrypt digest.

    Returns ``False`` — rather than raising — for an over-long candidate. No
    password beyond 72 bytes can have produced a hash through :func:`hash_password`,
    so verification cannot legitimately succeed; and under bcrypt 5 `checkpw`
    would raise, turning a bad input into a 500. Refusing is a *chosen*
    behaviour, not a swallowed error.

    Verifies digests written by passlib without any migration: both write the
    same `$2b$` format, proven by
    `tests/test_auth_fixture_fastpath.py::test_precomputed_hash_really_is_testpass`,
    which pins a passlib-generated hash.
    """
    if is_password_too_long(plain):
        return False
    return bcrypt.checkpw(plain.encode("utf-8"), hashed.encode("utf-8"))


def _serializer() -> URLSafeTimedSerializer:
    return URLSafeTimedSerializer(get_settings().app_secret_key)


def create_session_cookie(response: Response, user_id: int) -> None:
    """Sign user_id into a cookie and set it on the response."""
    token = _serializer().dumps({"user_id": user_id})
    settings = get_settings()
    is_prod = settings.app_env == "production"
    response.set_cookie(
        key=SESSION_COOKIE,
        value=token,
        max_age=SESSION_MAX_AGE,
        httponly=True,
        samesite="strict",
        secure=is_prod,
        path="/",
    )


def clear_session_cookie(response: Response) -> None:
    response.delete_cookie(key=SESSION_COOKIE, path="/")


def get_user_id_from_cookie(request: Request) -> Optional[int]:
    """Read and validate the session cookie. Returns the user_id
    or None if the cookie is missing / expired / tampered."""
    token = request.cookies.get(SESSION_COOKIE)
    if not token:
        return None
    try:
        payload = _serializer().loads(token, max_age=SESSION_MAX_AGE)
        return payload.get("user_id")
    except (BadSignature, Exception):
        return None


def get_current_user(request: Request, db: Session) -> Optional[User]:
    """Full user lookup from the cookie. Returns the User object
    or None. Used by the auth dependency."""
    user_id = get_user_id_from_cookie(request)
    if user_id is None:
        return None
    user = db.execute(
        select(User).where(User.id == user_id, User.is_active.is_(True))
    ).scalar_one_or_none()
    return user


RESET_TOKEN_MAX_AGE = 3600  # 1 hour


def create_reset_token(user_id: int) -> str:
    """Create a signed, time-limited token for password reset."""
    return _serializer().dumps({"user_id": user_id, "purpose": "reset"})


def verify_reset_token(token: str, max_age: int = RESET_TOKEN_MAX_AGE) -> int | None:
    """Verify a reset token. Returns user_id if valid, None otherwise."""
    if max_age <= 0:
        return None
    try:
        payload = _serializer().loads(token, max_age=max_age)
        if payload.get("purpose") != "reset":
            return None
        return payload.get("user_id")
    except (BadSignature, Exception):
        return None
