"""Sb_DEPENDENCY_LOCK_AUTHORITY_01 — the lock is the install contract, enforced.

WHY
---
Before this build, `requirements-lock.txt` was generated, committed, checked for
*parsing* — and read by nothing. CI (`ci.yml:90`, `:241`) and the production VPS
(`deploy_prod.sh:183`) both installed `requirements.txt`, whose ranges are open
(`fastapi>=0.110`, `sqlalchemy>=2.0`, …). Measured on 2026-08-18: **13 of 29
packages** differed between the declared lock and an environment installed that
way.

The consequence was not cosmetic. The pipeline pins the *code* to an exact SHA
and refuses to deploy a moving branch — while the *dependency tree* was resolved
fresh on every install. Two deploys of the same SHA could ship different
libraries.

These guards keep the two files, CI and prod pointing at the same contract.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CI = ROOT / ".github" / "workflows" / "ci.yml"
DEPLOY = ROOT / "scripts" / "deploy_prod.sh"
REGEN = ROOT / "scripts" / "regen_lockfile.sh"
DRIFT = ROOT / "scripts" / "check_lock_drift.py"
SOURCE = ROOT / "requirements.txt"
LOCK = ROOT / "requirements-lock.txt"
BASELINE = ROOT / "docs" / "SECURITY_BASELINE.md"

TARGET_PYTHON = "3.11"


def _uncommented(path: Path, comment: str = "#") -> str:
    """Strip whole-line comments — guards must read directives, not prose."""
    return "\n".join(
        line for line in path.read_text(encoding="utf-8").splitlines()
        if not line.strip().startswith(comment)
    )


# ───────────── A1 — CI installs the lock ─────────────

def test_a1_ci_installs_the_lockfile():
    directives = _uncommented(CI)
    assert "pip install -r requirements-lock.txt" in directives


def test_a1_no_ci_step_installs_the_source_spec():
    """The open-range file must never be what gets installed."""
    offenders = [
        line.strip()
        for line in _uncommented(CI).splitlines()
        if re.search(r"pip install\s+(-\S+\s+)*-r\s+requirements\.txt", line)
    ]
    assert offenders == [], f"CI still installs the source spec: {offenders}"


def test_a1_both_runtime_jobs_were_converted():
    """Sharded tests and the acceptance job each have their own install step."""
    assert _uncommented(CI).count("pip install -r requirements-lock.txt") == 2


# ───────────── A2 — production installs the lock ─────────────

def test_a2_deploy_installs_the_lockfile():
    directives = _uncommented(DEPLOY)
    assert "requirements-lock.txt" in directives
    assert not re.search(r'install .*-r "\$\{APP_DIR\}/requirements\.txt"', directives)


def test_a2_deploy_fails_loudly_when_the_lock_is_missing():
    """A SHA predating this sprint has no lock — say so instead of guessing."""
    assert "requirements-lock.txt absent" in DEPLOY.read_text(encoding="utf-8")


def test_a6_ci_and_prod_install_the_same_file():
    """The whole point: one install contract, two consumers."""
    assert "requirements-lock.txt" in _uncommented(CI)
    assert "requirements-lock.txt" in _uncommented(DEPLOY)


# ───────────── A3 — the lock is generated, for the right Python ─────────────

def test_a3_lock_declares_the_target_python():
    header = LOCK.read_text(encoding="utf-8")[:400]
    assert f"--python-version {TARGET_PYTHON}" in header, (
        "the lock must state which interpreter it was resolved for — it carries "
        "no environment markers, so it is only valid for that one"
    )


def test_a3_regen_script_pins_the_same_target():
    assert f'TARGET_PYTHON="{TARGET_PYTHON}"' in REGEN.read_text(encoding="utf-8")


def test_a3_regen_refuses_a_mismatched_interpreter():
    """pip-compile resolves for the running interpreter; a wrong lock is worse
    than a stale one now that CI and prod install it."""
    src = REGEN.read_text(encoding="utf-8")
    assert "uv pip compile" in src
    assert "--python-version" in src
    assert 'if [ "${RUNNING}" != "${TARGET_PYTHON}" ]' in src


def test_a3_ci_python_matches_the_lock_target():
    declared = set(re.findall(r'python-version:\s*"([^"]+)"', CI.read_text(encoding="utf-8")))
    assert declared == {TARGET_PYTHON}, (
        f"CI runs Python {sorted(declared)} but the lock targets {TARGET_PYTHON}"
    )


def test_lock_is_not_hand_editable_in_practice():
    """Every pin must carry a provenance comment, as generators emit."""
    body = LOCK.read_text(encoding="utf-8")
    assert "autogenerated" in body.lower() or "generated" in body.lower()
    assert body.count("# via") >= 20


# ───────────── A4 — drift is detected ─────────────

def test_a4_drift_checker_passes_on_the_committed_pair():
    result = subprocess.run(
        [sys.executable, str(DRIFT)], capture_output=True, text=True, check=False, cwd=ROOT
    )
    assert result.returncode == 0, result.stdout + result.stderr


def test_a4_ci_runs_the_drift_check_as_blocking():
    ci = CI.read_text(encoding="utf-8")
    assert "check_lock_drift.py" in ci
    step = ci[ci.index("check_lock_drift.py") - 700:ci.index("check_lock_drift.py")]
    assert "continue-on-error" not in step, "the drift check must not be advisory"


def test_a4_every_declared_dependency_is_pinned():
    from importlib import import_module

    sys.path.insert(0, str(ROOT))
    module = import_module("scripts.check_lock_drift")
    source, pins = module._source_requirements(), module._lock_pins()
    missing = [name for name in source if name not in pins]
    assert missing == [], f"declared but not pinned: {missing}"


def test_a4_the_bcrypt_ceiling_survives_regeneration():
    """`bcrypt>=4.0,<5` exists because passlib 1.7.4 breaks on bcrypt 5."""
    pins = dict(re.findall(r"^([a-z0-9_.\-]+)==([^\s]+)$", LOCK.read_text(encoding="utf-8"), re.M))
    major = int(pins["bcrypt"].split(".")[0])
    assert major < 5, f"lock pins bcrypt {pins['bcrypt']} — passlib 1.7.4 cannot load it"


# ───────────── A5 — the "advisory" framing is gone ─────────────

#: Phrases that would tell a reader the lockfile still governs nothing.
#: Matched literally: an earlier version of this guard flagged any line pairing
#: "advisory" with "lock", which caught the ruff *budget locked* comment and the
#: very comments explaining that the step USED to be advisory. A guard that reads
#: narration instead of claims is noise.
STALE_CLAIMS = (
    "`requirements-lock.txt` (advisory)",
    "Statut V1 : advisory",
    "advisory — Sb_26.4",
    "n'est pas encore** utilisé",
    "NOT yet used by deploy_prod.sh",
)


def test_a5_no_document_still_claims_the_lockfile_is_advisory():
    offenders: list[str] = []
    for path in (CI, REGEN, BASELINE, DEPLOY):
        text = path.read_text(encoding="utf-8")
        offenders += [
            f"{path.relative_to(ROOT)}: {claim!r}" for claim in STALE_CLAIMS if claim in text
        ]
    assert offenders == [], f"the lockfile is still described as advisory: {offenders}"


def test_a5_the_baseline_states_the_lockfile_is_authoritative():
    baseline = BASELINE.read_text(encoding="utf-8")
    assert "AUTORITAIRE" in baseline
    assert "pip install -r requirements-lock.txt" in baseline


def test_a5_regen_script_no_longer_says_the_lock_is_unused():
    src = REGEN.read_text(encoding="utf-8")
    assert "NOT yet used by deploy_prod.sh" not in src
    assert "AUTHORITATIVE" in src


# ───────────── A8 / A9 — scope ─────────────

def test_a8_no_ci_action_version_was_touched():
    """upload/download-artifact and gitleaks-action are explicitly out of scope."""
    ci = CI.read_text(encoding="utf-8")
    assert "actions/checkout@v4" in ci
    assert "actions/setup-python@v5" in ci
    assert "actions/upload-artifact@v4" in ci
    assert "actions/download-artifact@v4" in ci
    assert "gitleaks/gitleaks-action@v2" in ci


def test_a9_the_source_spec_is_unchanged_in_substance():
    """requirements.txt stays the human-edited declaration."""
    declared = [
        line.strip() for line in SOURCE.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]
    assert "bcrypt>=4.0,<5" in declared
    assert any(line.startswith("fastapi") for line in declared)
