"""add excluded_from_stats to workout_sessions

Revision ID: b6bbb9adc05a
Revises: ef67ec29e3e0
Create Date: 2026-04-09 19:06:30.268294+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6bbb9adc05a'
down_revision: Union[str, Sequence[str], None] = 'ef67ec29e3e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('excluded_from_stats', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.drop_column('excluded_from_stats')

    # ### end Alembic commands ###
