"""initial baseline

Revision ID: ef67ec29e3e0
Revises: 
Create Date: 2026-04-08 19:57:04.808028+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef67ec29e3e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('method_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('reference_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('seeded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('workout_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('focus', sa.String(length=128), nullable=False),
    sa.Column('cardio_note', sa.Text(), nullable=True),
    sa.Column('suggested_label', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('template_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('set_scheme', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'position', name='uq_template_exercise_position')
    )
    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('template_slug_snapshot', sa.String(length=64), nullable=False),
    sa.Column('template_name_snapshot', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('concentration', sa.String(length=16), nullable=True),
    sa.Column('global_state', sa.String(length=16), nullable=True),
    sa.Column('bodyweight_kg', sa.Float(), nullable=True),
    sa.Column('free_note', sa.String(length=280), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_workout_sessions_started_at', ['started_at'], unique=False)

    op.create_table('rep_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_index', sa.Integer(), nullable=False),
    sa.Column('min_reps', sa.Integer(), nullable=False),
    sa.Column('max_reps', sa.Integer(), nullable=False),
    sa.Column('technique', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['template_exercise_id'], ['template_exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_exercise_id', 'set_index', name='uq_rep_target_set')
    )
    op.create_table('session_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('template_exercise_id', sa.Integer(), nullable=True),
    sa.Column('exercise_code_snapshot', sa.String(length=16), nullable=False),
    sa.Column('exercise_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('success_score', sa.Integer(), nullable=True),
    sa.Column('muscle_sensation', sa.String(length=16), nullable=True),
    sa.Column('free_note', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_exercise_id'], ['template_exercises.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'position', name='uq_session_exercise_position')
    )
    op.create_table('set_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_exercise_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('set_index', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('technique', sa.String(length=8), nullable=True),
    sa.Column('execution_quality', sa.String(length=16), nullable=True),
    sa.Column('reps_target', sa.String(length=16), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_exercise_id'], ['session_exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_exercise_id', 'kind', 'set_index', name='uq_set_log_kind_index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('set_logs')
    op.drop_table('session_exercises')
    op.drop_table('rep_targets')
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_workout_sessions_started_at')

    op.drop_table('workout_sessions')
    op.drop_table('template_exercises')
    op.drop_table('workout_templates')
    op.drop_table('reference_docs')
    op.drop_table('method_rules')
    # ### end Alembic commands ###
