-- Sb_26.2 — contractual schema snapshot.
-- Generated by scripts/generate_schema_snapshot.py from alembic head.
-- Do NOT edit manually. Regenerate after every Alembic migration:
--     python scripts/generate_schema_snapshot.py
-- The CI check (scripts/check_schema_snapshot.py) fails on any diff.

-- index: ix_body_measurements_user_date
CREATE INDEX ix_body_measurements_user_date ON body_measurements (user_id, measured_at);

-- index: ix_session_exercises_session_id
CREATE INDEX ix_session_exercises_session_id ON session_exercises (session_id);

-- index: ix_set_logs_exercise_kind_completed
CREATE INDEX ix_set_logs_exercise_kind_completed ON set_logs (session_exercise_id, kind, completed);

-- index: ix_workout_sessions_started_at
CREATE INDEX ix_workout_sessions_started_at ON workout_sessions (started_at);

-- index: ix_workout_sessions_user_id
CREATE INDEX ix_workout_sessions_user_id ON workout_sessions (user_id);

-- index: ix_ws_user_status_excl_started
CREATE INDEX ix_ws_user_status_excl_started ON workout_sessions (user_id, status, excluded_from_stats, started_at);

-- table: body_measurements
CREATE TABLE "body_measurements" ( id INTEGER NOT NULL, user_id INTEGER NOT NULL, measured_at DATETIME NOT NULL, weight_kg FLOAT, chest_cm FLOAT, waist_cm FLOAT, calf_cm FLOAT, created_at DATETIME DEFAULT (CURRENT_TIMESTAMP) NOT NULL, arm_cm_left FLOAT, arm_cm_right FLOAT, thigh_cm_left FLOAT, thigh_cm_right FLOAT, hip_cm FLOAT, neck_cm FLOAT, PRIMARY KEY (id), FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE );

-- table: method_rules
CREATE TABLE method_rules ( id INTEGER NOT NULL, slug VARCHAR(64) NOT NULL, position INTEGER NOT NULL, title VARCHAR(128) NOT NULL, body TEXT NOT NULL, PRIMARY KEY (id), UNIQUE (slug) );

-- table: readiness_entries
CREATE TABLE readiness_entries ( id INTEGER NOT NULL, user_id INTEGER NOT NULL, recorded_on DATE NOT NULL, sleep_quality INTEGER NOT NULL, fatigue_level INTEGER NOT NULL, soreness_level INTEGER NOT NULL, stress_level INTEGER NOT NULL, motivation_level INTEGER NOT NULL, resting_hr INTEGER, note TEXT, created_at DATETIME DEFAULT (CURRENT_TIMESTAMP) NOT NULL, PRIMARY KEY (id), FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, CONSTRAINT uq_readiness_user_day UNIQUE (user_id, recorded_on) );

-- table: reference_docs
CREATE TABLE reference_docs ( id INTEGER NOT NULL, version VARCHAR(64) NOT NULL, title VARCHAR(255) NOT NULL, seeded_at DATETIME DEFAULT (CURRENT_TIMESTAMP) NOT NULL, PRIMARY KEY (id), UNIQUE (version) );

-- table: rep_targets
CREATE TABLE rep_targets ( id INTEGER NOT NULL, template_exercise_id INTEGER NOT NULL, set_index INTEGER NOT NULL, min_reps INTEGER NOT NULL, max_reps INTEGER NOT NULL, technique VARCHAR(8), PRIMARY KEY (id), FOREIGN KEY(template_exercise_id) REFERENCES template_exercises (id) ON DELETE CASCADE, CONSTRAINT uq_rep_target_set UNIQUE (template_exercise_id, set_index) );

-- table: session_exercises
CREATE TABLE session_exercises ( id INTEGER NOT NULL, session_id INTEGER NOT NULL, template_exercise_id INTEGER, exercise_code_snapshot VARCHAR(16) NOT NULL, exercise_name_snapshot VARCHAR(255) NOT NULL, position INTEGER NOT NULL, success_score INTEGER, muscle_sensation VARCHAR(16), free_note VARCHAR(140), substituted_name VARCHAR(255), implicit_label VARCHAR(32), implicit_label_computed_at DATETIME, PRIMARY KEY (id), FOREIGN KEY(session_id) REFERENCES workout_sessions (id) ON DELETE CASCADE, FOREIGN KEY(template_exercise_id) REFERENCES template_exercises (id) ON DELETE SET NULL, CONSTRAINT uq_session_exercise_position UNIQUE (session_id, position) );

-- table: set_logs
CREATE TABLE set_logs ( id INTEGER NOT NULL, session_exercise_id INTEGER NOT NULL, kind VARCHAR(8) NOT NULL, set_index INTEGER NOT NULL, weight_kg FLOAT, reps INTEGER, technique VARCHAR(8), execution_quality VARCHAR(16), reps_target VARCHAR(16), completed BOOLEAN NOT NULL, PRIMARY KEY (id), FOREIGN KEY(session_exercise_id) REFERENCES session_exercises (id) ON DELETE CASCADE, CONSTRAINT uq_set_log_kind_index UNIQUE (session_exercise_id, kind, set_index) );

-- table: squad_challenges
CREATE TABLE squad_challenges ( id INTEGER NOT NULL, squad_id INTEGER NOT NULL, created_by INTEGER NOT NULL, title VARCHAR(128) NOT NULL, metric VARCHAR(32) NOT NULL, starts_at DATE NOT NULL, ends_at DATE NOT NULL, created_at DATETIME DEFAULT (CURRENT_TIMESTAMP) NOT NULL, PRIMARY KEY (id), FOREIGN KEY(created_by) REFERENCES users (id), FOREIGN KEY(squad_id) REFERENCES squads (id) ON DELETE CASCADE );

-- table: squad_invite_codes
CREATE TABLE squad_invite_codes ( id INTEGER NOT NULL, squad_id INTEGER NOT NULL, code VARCHAR(12) NOT NULL, created_by INTEGER NOT NULL, expires_at DATETIME NOT NULL, used_by INTEGER, used_at DATETIME, PRIMARY KEY (id), FOREIGN KEY(squad_id) REFERENCES squads (id) ON DELETE CASCADE, FOREIGN KEY(created_by) REFERENCES users (id), FOREIGN KEY(used_by) REFERENCES users (id), UNIQUE (code) );

-- table: squad_memberships
CREATE TABLE squad_memberships ( id INTEGER NOT NULL, squad_id INTEGER NOT NULL, user_id INTEGER NOT NULL, role VARCHAR(16) DEFAULT 'member' NOT NULL, joined_at DATETIME DEFAULT (CURRENT_TIMESTAMP) NOT NULL, PRIMARY KEY (id), FOREIGN KEY(squad_id) REFERENCES squads (id) ON DELETE CASCADE, FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, CONSTRAINT uq_squad_membership UNIQUE (squad_id, user_id) );

-- table: squad_shared_sessions
CREATE TABLE squad_shared_sessions ( id INTEGER NOT NULL, squad_id INTEGER NOT NULL, user_id INTEGER NOT NULL, session_id INTEGER NOT NULL, created_at DATETIME DEFAULT (CURRENT_TIMESTAMP) NOT NULL, PRIMARY KEY (id), FOREIGN KEY(session_id) REFERENCES workout_sessions (id), FOREIGN KEY(squad_id) REFERENCES squads (id) ON DELETE CASCADE, FOREIGN KEY(user_id) REFERENCES users (id) );

-- table: squad_template_recommendations
CREATE TABLE squad_template_recommendations ( id INTEGER NOT NULL, squad_id INTEGER NOT NULL, user_id INTEGER NOT NULL, template_slug VARCHAR(64) NOT NULL, template_name VARCHAR(128) NOT NULL, note VARCHAR(280), created_at DATETIME DEFAULT (CURRENT_TIMESTAMP) NOT NULL, PRIMARY KEY (id), FOREIGN KEY(squad_id) REFERENCES squads (id) ON DELETE CASCADE, FOREIGN KEY(user_id) REFERENCES users (id) );

-- table: squads
CREATE TABLE squads ( id INTEGER NOT NULL, name VARCHAR(64) NOT NULL, owner_id INTEGER NOT NULL, created_at DATETIME DEFAULT (CURRENT_TIMESTAMP) NOT NULL, PRIMARY KEY (id), FOREIGN KEY(owner_id) REFERENCES users (id) ON DELETE CASCADE, UNIQUE (name) );

-- table: template_exercises
CREATE TABLE template_exercises ( id INTEGER NOT NULL, template_id INTEGER NOT NULL, position INTEGER NOT NULL, code VARCHAR(8) NOT NULL, name VARCHAR(255) NOT NULL, set_scheme VARCHAR(255) NOT NULL, notes TEXT, substitutes_json TEXT, machine_slug VARCHAR(64), machine_family VARCHAR(64), PRIMARY KEY (id), FOREIGN KEY(template_id) REFERENCES workout_templates (id) ON DELETE CASCADE, CONSTRAINT uq_template_exercise_position UNIQUE (template_id, position) );

-- table: users
CREATE TABLE "users" ( id INTEGER NOT NULL, username VARCHAR(64) NOT NULL, password_hash VARCHAR(255) NOT NULL, is_active BOOLEAN NOT NULL, created_at DATETIME DEFAULT (CURRENT_TIMESTAMP) NOT NULL, height_cm INTEGER, weight_kg FLOAT, resting_hr INTEGER, waist_cm FLOAT, bp_systolic INTEGER, bp_diastolic INTEGER, email VARCHAR(255), PRIMARY KEY (id), CONSTRAINT uq_users_email UNIQUE (email), UNIQUE (username) );

-- table: workout_sessions
CREATE TABLE "workout_sessions" ( id INTEGER NOT NULL, template_id INTEGER, template_slug_snapshot VARCHAR(64) NOT NULL, template_name_snapshot VARCHAR(128) NOT NULL, started_at DATETIME NOT NULL, ended_at DATETIME, status VARCHAR(16) NOT NULL, concentration VARCHAR(16), global_state VARCHAR(16), bodyweight_kg FLOAT, free_note VARCHAR(280), created_at DATETIME DEFAULT (CURRENT_TIMESTAMP) NOT NULL, excluded_from_stats BOOLEAN NOT NULL, user_id INTEGER, cardio_duration_min INTEGER, cardio_bpm_avg INTEGER, cardio_machine_calories INTEGER, cardio_machine_type VARCHAR(32), creation_source VARCHAR(16), scoring_version INTEGER DEFAULT '1' NOT NULL, PRIMARY KEY (id), CONSTRAINT fk_workout_sessions_user_id FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, FOREIGN KEY(template_id) REFERENCES workout_templates (id) ON DELETE SET NULL );

-- table: workout_templates
CREATE TABLE workout_templates ( id INTEGER NOT NULL, slug VARCHAR(64) NOT NULL, name VARCHAR(128) NOT NULL, kind VARCHAR(16) NOT NULL, focus VARCHAR(128) NOT NULL, cardio_note TEXT, suggested_label VARCHAR(128), catalog_section VARCHAR(32) DEFAULT 'core' NOT NULL, display_order INTEGER DEFAULT '0' NOT NULL, PRIMARY KEY (id), UNIQUE (slug) );
