#!/usr/bin/env python3
"""Sb_26.2 — Generate a contractual schema snapshot from alembic head.

Workflow:
1. Spin up a temp SQLite DB.
2. Run `alembic upgrade head` against it.
3. Dump the resulting schema (CREATE TABLE + CREATE INDEX) sorted.
4. Write to `data/schema_snapshot.sql` (or path passed as arg).

The snapshot is the canonical schema contract — any drift is detected by
`scripts/check_schema_snapshot.py` (Sb_26.2 §3).

Usage:
    python scripts/generate_schema_snapshot.py
    python scripts/generate_schema_snapshot.py --out data/schema_snapshot.sql
"""
from __future__ import annotations

import argparse
import sqlite3
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = ROOT / "data" / "schema_snapshot.sql"


def _build_snapshot(db_path: Path) -> str:
    """Read all CREATE statements from sqlite_master, sort, normalize."""
    conn = sqlite3.connect(str(db_path))
    try:
        cur = conn.execute(
            "SELECT type, name, sql FROM sqlite_master "
            "WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' "
            "AND name != 'alembic_version' "
            "ORDER BY type, name"
        )
        rows = cur.fetchall()
    finally:
        conn.close()

    lines: list[str] = [
        "-- Sb_26.2 — contractual schema snapshot.",
        "-- Generated by scripts/generate_schema_snapshot.py from alembic head.",
        "-- Do NOT edit manually. Regenerate after every Alembic migration:",
        "--     python scripts/generate_schema_snapshot.py",
        "-- The CI check (scripts/check_schema_snapshot.py) fails on any diff.",
        "",
    ]
    for type_, name, sql in rows:
        normalized = " ".join(sql.split())
        lines.append(f"-- {type_}: {name}")
        lines.append(f"{normalized};")
        lines.append("")
    return "\n".join(lines)


def _alembic_upgrade(db_url: str) -> None:
    from alembic import command
    from alembic.config import Config

    cfg = Config(str(ROOT / "alembic.ini"))
    cfg.set_main_option("sqlalchemy.url", db_url)
    command.upgrade(cfg, "head")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_OUT,
        help="Output file (default: data/schema_snapshot.sql)",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Print to stdout instead of writing.",
    )
    args = parser.parse_args()

    tmp_dir = tempfile.mkdtemp(prefix="schema-snapshot-")
    db_path = Path(tmp_dir) / "snapshot.db"
    db_url = f"sqlite:///{db_path}"

    print(f"[snapshot] alembic upgrade head on {db_url}", file=sys.stderr)
    _alembic_upgrade(db_url)
    snapshot = _build_snapshot(db_path)

    if args.stdout:
        print(snapshot)
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(snapshot, encoding="utf-8")
    print(f"[snapshot] wrote {args.out} ({len(snapshot.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
