#!/usr/bin/env bash
# Sb_DEPENDENCY_LOCK_AUTHORITY_01 — regenerate requirements-lock.txt from requirements.txt.
#
#   bash scripts/regen_lockfile.sh
#   git add requirements-lock.txt
#
# THE LOCKFILE IS AUTHORITATIVE. CI and the production VPS both install from it:
#   .github/workflows/ci.yml   — pip install -r requirements-lock.txt
#   scripts/deploy_prod.sh     — pip install -r requirements-lock.txt
# `requirements.txt` stays the SOURCE SPEC (open ranges, human-edited); this file
# is the INSTALL CONTRACT (exact pins, generated). Never hand-edit the lock.
#
# WHY THE TARGET VERSION IS PINNED HERE
# -------------------------------------
# A lock produced without environment markers is only valid for the interpreter
# that resolved it. The previous lock carried the header "autogenerated by
# pip-compile with Python 3.14" while CI runs 3.11 — the two disagreed, silently,
# because nothing installed from the lock. Now that something does, the target
# must be explicit and must match CI.

set -euo pipefail

cd "$(dirname "$0")/.."

# Must match python-version in .github/workflows/ci.yml (checked by
# scripts/check_lock_drift.py, so the two cannot drift apart unnoticed).
TARGET_PYTHON="3.11"

if command -v uv &>/dev/null; then
    # uv resolves FOR a target version, whatever interpreter is running it.
    # That is the only way to produce a 3.11 lock from a 3.14 shell.
    echo "[regen_lockfile] uv, résolution pour Python ${TARGET_PYTHON}"
    uv pip compile \
        --python-version "${TARGET_PYTHON}" \
        --strip-extras \
        --quiet \
        --output-file requirements-lock.txt \
        requirements.txt
else
    # pip-compile resolves for the RUNNING interpreter only. Refuse rather than
    # emit a lock for the wrong version — a wrong lock is worse than no lock now
    # that CI and prod install from it.
    RUNNING="$(python -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
    if [ "${RUNNING}" != "${TARGET_PYTHON}" ]; then
        echo "[regen_lockfile] ERREUR : pip-compile résout pour l'interpréteur courant (${RUNNING})," >&2
        echo "                 or la cible est ${TARGET_PYTHON}. Installe uv, ou relance sous Python ${TARGET_PYTHON}." >&2
        exit 1
    fi
    command -v pip-compile &>/dev/null || pip install --quiet pip-tools
    echo "[regen_lockfile] pip-compile sous Python ${RUNNING}"
    pip-compile \
        --strip-extras \
        --quiet \
        --output-file=requirements-lock.txt \
        requirements.txt
fi

echo "[regen_lockfile] requirements-lock.txt régénéré ($(grep -c '==' requirements-lock.txt) paquets épinglés)"
echo "[regen_lockfile] vérification de cohérence :"
python scripts/check_lock_drift.py
